[breaking]
color = "ffcc00"
name = "breaking"
description = "Breaking change."

[bug]
color = "d73a4a"
name = "bug"
description = "Something isn't working"

[dependencies]
color = "0366d6"
name = "dependencies"
description = "Pull requests that update a dependency file"

[github_actions]
color = "000000"
name = "github_actions"
description = "Update of github actions"

[documentation]
color = "1bc4a5"
name = "documentation"
description = "Improvements or additions to documentation"

[duplicate]
color = "cfd3d7"
name = "duplicate"
description = "This issue or pull request already exists"

[enhancement]
color = "a2eeef"
name = "enhancement"
description = "New feature or request"

["good first issue"]
color = "7057ff"
name = "good first issue"
description = "Good for newcomers"

["help wanted"]
color = "008672"
name = "help wanted"
description = "Extra attention is needed"

[invalid]
color = "e4e669"
name = "invalid"
description = "This doesn't seem right"

[nochangelog]
color = "555555"
name = "nochangelog"
description = "Exclude pull requests from changelog"

[question]
color = "d876e3"
name = "question"
description = "Further information is requested"

[removed]
color = "e99695"
name = "removed"
description = "Removed piece of functionalities."

[tests]
color = "bfd4f2"
name = "tests"
description = "CI, CD and testing related changes"

[wontfix]
color = "ffffff"
name = "wontfix"
description = "This will not be worked on"

[discussion]
color = "c2e0c6"
name = "discussion"
description = "Some discussion around the project"

[hacktoberfest]
color = "ffa663"
name = "hacktoberfest"
description = "Good issues for Hacktoberfest"

[answered]
color = "0ee2b6"
name = "answered"
description = "Automatically closes as answered after a delay"

[waiting]
color = "5f7972"
name = "waiting"
description = "Automatically closes if no answer after a delay"

[fund]
color = "0E8A16"
name = "fund"
description = "Add a section linking to polar.sh for funding the issue."
