name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "15 11 3 1-9,11-12 *"

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/uv-upgrade.yml@401ce9080ccf24b0779162677b52a6276ef4e4d1 # v1
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}
