name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "15 11 3 1-9,11-12 *"

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/uv-upgrade.yml@f62ef26d5b2705fbcbf9c48ed4619f055efa3481 # v1
    secrets:
      gh_pat: ${{ secrets.GH_PAT }}
